main: dk.tandhjulet.SchematicPaster
name: SchematicPaster
author: Tandhjulet
version: ${project.version}
description: Fastest schematic paster

commands:
  paste:
    description: Pastes a schematic
    usage: /<command>